### PR TITLE
This is to fix Issue #274

### PR DESCRIPTION
**Pull request by nellyk**
@mwangiann Hi this is the pull request that will resolve issue this issues https://github.com/rapidftr/tracker/issues/196

### CODE REVIEW

**Comment by mwangiann** [comment]
Hi,

Sorry am on leave and am somewhere without my laptop. Can't have a look at
it now, till next week.

Am cc'ing Prasanna so that he can Have a look at the pull request.

**Comment by sriprasanna** [comment]
@nellyk Would be great if you can add Cucumber tests for this, so that we can make sure this bug doesn't get introduced again.

**Comment by nellyk** [comment]
@sriprasanna and @mwangiann  we did a new pull request, kindly have a look at our cucumber test, hope it does make sense we had a bit of difficulty working on it

**Comment by tomclement** [comment]
Hi @nellyk - looks like the build is failing due to some Rubocop offenses. Take a look at the below information from [Travis](https://travis-ci.org/rapidftr/RapidFTR/jobs/78267162):

```
Offenses:
features/step_definitions/enquiry_setup_steps.rb:39:47: W: Unused block argument - arg1. You can omit the argument if you don't care about it.
Then /^I should see "(.*?)" on the page$/ do |arg1|
                                              ^^^^
features/step_definitions/web_steps.rb:346:52: W: Unused block argument - arg1. You can omit the argument if you don't care about it.
When(/^I follow "(.*?)" for enquiry records$/) do |arg1|
                                                   ^^^^
356 files inspected, 2 offenses detected
RuboCop failed!
```

**Comment by nellyk** [comment]
Hi @tomclement  Thanks for that we looking into it

**Comment by nellyk** [comment]
@sriprasanna  we have fixed the bug stated in issue "Missing translations in permissions filters #274"

**Pull request closed without merging**
